brew "bat"
brew "dust"
brew "eza"
brew "fd"
brew "fzf"
brew "gping"
brew "htop"
brew "httpie"
brew "iputils", link: false  # Kept keg-only (link: false) — gping pulls this as a dep on Linux. Not linking prevents brew's iputils from shadowing the system ping in WSL.
brew "jq"
brew "ripgrep"
brew "tldr"
brew "trippy"
brew "yq"
